### ISSUE TITLE
--match string containing double quotes cannot find the given argument

### ISSUE THREAD

**Issue by corang** [capitalone/bash_shell_mock#14]
The easiest example of this is in the sample-bats directory, if you look at the "sample.sh failure" test, modifying the status of the grep command from 1 to 0 does not affect the outcome of the test. This is because shellmock cannot find the grep command to begin with. Easy way to see this is to reverse the if conditional on teardown to see the shellmock error log. 

The current workaround that I've been using is to utilize the '--type partial' flag and not look for double quotes in the --match argument.

**Comment by ckstettler** [comment]
I totally see what you are describing.  I will dig into it to isolate the issue.  I suspect the " are getting on the input side somewhere down the line.  Thank you for taking the time to submit the issue.

**Comment by ckstettler** [comment]
I understand the issue better, however,  whats the best way to solve it?  When mocking I use a quoted string that contains all of the arguments and some could contain quotes.  The inner quotes around the arguments are visible and part of the data that currently gets matched.  However then the mock is run I can not capture the raw quotes that get passed in a runtime.  The shell will eat those and I just have the arguments.

I think I need to maintain the quoted string approach when defining the mock, but store as an array of arguments instead of a quoted string.  When match I should make sure the arg array matches.

The one issue with that is the regex matcher.  To use that as intended I would need to reconstruct the arg list as a string before matching.  When doing that when should I add  quotes to the arglist?  Maybe when there is white space in the arg? or for simplicity I could leave them out of together, but that is not quite right.  I would rather account for them but I would never be able to account for ' vs ".  I would need to use one or the other when matching.

**Comment by ckstettler** [comment]
The latest version has support for passing and validating quoted arguments.  There are some limitations ie the tool can not distinguish between single or double quotes so when verifying the mock you must always use double quotes.

**Comment by ckstettler** [comment]
PR#25 resolves this issue with some limitations. The tool can detect quotes have been used, however, can not distinguish between single or double quotes.  As a result when verifying matches we normalized on double quotes.
