### ISSUE TITLE
mock custom functions

### ISSUE THREAD

**Issue by baniocarpentercode42** [capitalone/bash_shell_mock#18]
If I have the following functions file:
functions_file.sh:
```helper_function(){
  docker_user="$1"
  docker_password="$2"
  docker_registry="$3"
  docker login -p ${docker_password} -u ${docker_user} ${registry}
}

main_function(){
    helper_function user1 password1 nonexsistent.domain.com
}
```

And the bats file:
```load 'libs/bats-support/load'
load 'libs/bats-assert/load'

setup() {
  . shellmock
  source functions_file.sh
  skipIfNot "$BATS_TEST_DESCRIPTION"
  shellmock_clean
}

teardown() {
  if [[ -z "$TEST_FUNCTION" ]]; then
    shellmock_clean
  fi
}

stub_functions() {
  shellmock_expect helper_function --match "user1 password1 registry.domain.com"
}

@test "main" {
  stub_functions
  run main_function
  assert_equal "$status" 0
}
```
I don't seem to be able to mock the function help_function

**Comment by ckstettler** [comment]
The mocking features were written to mock script or commands that are available and in the PATH. Every mocked interface becomes a file on disk to a path that is added to the beginning of the path.  If I am following correctly, you have defined a function that lives within the same file as the main_function.

In that case bash is going to see the function before it searches the PATH so that mock will never be called. 

I ran a quick test to verify the issue.  I created a file called file1 

- file1
```bash
file2() {
    echo 'file2 function'
}
file2
```
- file2
```bash
echo 'file2 file'
```

I set the PATH=.:$PATH and invoked file1.  It echoed "file2 function". Which means the local function was called before the path was searched.  If this simple shell example doesn't work then the mocking tool will never work.  We would somehow need to tell the shell to prefer the  command over the function.

I even tried sourcing a file that contained the "mocked" functions, but if the function name existed in the local file and in the "overridden" functions file, the shell still took the local one first.

I don't see a simple solution given the constraints of bash.

**Comment by baniocarpentercode42** [comment]
@ckstettler thank you for looking into this issue.  Your explanation makes sense given how shellmock 
 and bash work.  Closing.

**Comment by CaptainQuirk** [comment]
Hey @ckstettler !

I just wanted to chime in on this issue ! 

Wouldn't it be possible for `shellmock` to actually give us a smal API that would allow us to do that in the following way : 


```sh
# my_script.sh
# the script I want to test with a `my_great_function` call I would like to mock
# the function being defined in a separate file

source $SHARE/functions/my-great-function

if ! my_great_function "she"; then
    exit 1
fi

exit 0

# -------------------------------------------------------------------#

# $SHARE/functions/my-great-function
# contains the function I would like to mock (dummy code)

my_great_function() {
    echo "$1|foo|bar" 

    return 0
}

# -------------------------------------------------------------------#

@test "It fails if my_great_function fails" {
    # GIVEN
   # shellmock would create a mocked function in a subdirectory `functions/my-great-function` of `tmpstubs/`
   shellmock_function my_great_function --match she --return 1 --path functions/my-great-function

   # We export a different SHARE variable so that we can source the mocked function created by
   # shellmock, via a `$SHELLMOCK_FN_STUBS` variable for example
   export SHARE=$SHELLMOCK_FN_STUBS

    # WHEN
    run my_script

    # THEN
    [  "$status" -eq 1 ]
}
```

Don't you think that it would solve the problem ?

**Comment by ckstettler** [comment]
I think this solution forces two things that will likely not be reasonable for many folks.

1) I have to reference my sources script via a common variable such as $SHARE in this case.  Thats not too bad I guess.
2) To have complete control I would have to store every function in its own file or at least everyone I want to be able to mock.

I typically put many functions into a single file.  You would need to mock them all or separate them.

**Comment by CaptainQuirk** [comment]
I agree with you, doing this would actually require more than a `$SHARE` variable. In my particular project, I have several function files : if I change the `$SHARE` variable once, it gets changed for all of them and all subsequent sourcing of files with `$SHARE` as part of their paths fail.

However, in my particular case, given the size of my codebase and my growing need for isolated function tests, I'll probably work on some `import` function that would make it possible to swap files.

In that case, wouldn't it be possible to swap a regular file with an override that sources the former and overrides just the function it needs to override (that could be done with a `unset -f <original-function>` right ?

```sh

# Regular function in my-script file
my_function() {

}

my_other_function() {

}

# Overriden function in file generated by shellmock
source "my-script"
unset -f my_function

my_function() {
    my_other_function
}
```

I may be way over my head with this. I'll try and make some tests in the following days !

**Comment by ckstettler** [comment]
unset is interesting.  I could see how this could work if my-script is the file being tested and the function being mocked is used within another function in the same file.

How would I test something like this for example though which was more of my use cases?

my-script
```
my_function() {
    echo "my function"
}
```

b.sh
```
source ./my-script

my_function
```

I guess the shellmock tool could allow you to define a function and also provides the home of the script that contains the function to be mocked.  The tool could clone the script and add the replaced function maybe?  It still wouldn't solve a scenario where you are trying to test something like:

b.sh
```
my_function() {
}


# Main
my_function
```

My reservation has been that I can not think of a way apart from writing or hooking into the bona-fide shell that covers every scenario.  I guess I could target the scenarios that are possible.

I will look at this a little today while I am addressing on of the open issues.

**Comment by CaptainQuirk** [comment]
I guess that this particular scenario should be considered out of the scope here. Maybe I'm a bit biased coming from an OOP world because I consider this kind of function to be a private function. I can live with that kind of functions not being mockable.

But in the event where I'm actually splitting my functions into meaningful pieces, I would consider only functions that are destined to be used by other part of the program (like a public API).

Does it make sense to you ?

On another matter, I think I remember having fiddled with the `env` function

```sh
env my_function() {

}
```
